### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by edwardabraham** [dragonfly-science/github-mirroring#1]
Hi @vizowl ... our installation no longer seems to be working.see the error messages on Deployhub.

**Comment by vizowl** [comment]
Something changed either in the permissions or the API which meant that the code which was installing webhooks on new repositories was failing. However, in the process of debugging this I discovered that github now has organization wide webhooks which is a much better place for this functionality.

**Comment by edwardabraham** [comment]
Organisation wide webhooks. Brilliant. You get to find out whenever anyone
does anything! Thanks.
